id: org.OverEngineer.CuteTales
command: CuteTales
runtime: org.kde.Platform
runtime-version: "6.8"
sdk: org.kde.Sdk

finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --filesystem=host
  - --device=dri

modules:
#  - name: libssh2
#    buildsystem: cmake
#    config-opts:
#      - -DCMAKE_BUILD_TYPE=Release
#      - CRYPTO_BACKEND=OpenSSL
#      - BUILD_EXAMPLES=OFF
#      - BUILD_TESTING=OFF
#    sources:
#      - sha256: 31469ccfc71a5247c926e3f0938e122cbb7a7a4a1bdf1cf2d3121f78b558d261
#        type: archive
#        url: https://github.com/libssh2/libssh2/archive/refs/tags/libssh2-1.10.0.tar.gz

  - name: CuteTales
    buildsystem: cmake-ninja
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DFLATPAK_BUILD=ON
    sources:
      - type: dir
        path: ../../../
